---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lasample
  labels:
    app: nginx
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16-perl
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "400m"  
        ports:
        - containerPort: 80
